version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
    restart: always
    environment:
      - REACT_APP_BACKEND_HOST=localhost
      - REACT_APP_BACKEND_PORT=3001
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db
    restart: always
    environment:
      - PORT=3001
      - DB_PORT=5432
      - DB_HOST=db
      - DB_NAME=ng_challenge_db
      - DB_USER=postgres
      - DB_PASS=123456
      - JWT_SECRET=secret@jwt
  db:
    image: postgres:15
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - /data:/var/lib/postgresql/data

volumes:
  data: {}